name: Build static binaries
description: Builds the static binary for a system

inputs:
  os:
    description: The system to build for (linux-amd64, linux-arm64, darwin-amd64 or darwin-arm64)
    required: true

runs:
  using: composite
  steps:
    - name: Build Castor static binary for ${{ inputs.os }}
      run: bin/castor "castor:static:${INPUTS_OS}"
      shell: bash
      env:
        INPUTS_OS: ${{ inputs.os }}

    - name: Ensure binary is OK (${{ inputs.os }})
      run: |
        set -e
        "./castor.${INPUTS_OS}" --version
        "./castor.${INPUTS_OS}" debug
      shell: bash
      env:
        INPUTS_OS: ${{ inputs.os }}
